checks:
  python:
    code_rating: true
    # duplicate_code: true
    basic_dangerous_default_value: true
    basic_eval_used: true
    basic_lost_exception: true
    classes_bad_classmethod_argument: true
    classes_bad_mcs_classmethod_argument: true
    classes_bad_mcs_method_argument: true
    classes_bad_staticmethod_argument: true
    classes_no_self_argument: true
    classes_protected_access: true
    classes_signature_differs: true
    variables_unpacking_non_sequence: true
    variables_undefined_variable: true
    variables_redefined_builtin: true
    variables_global_at_module_level: true
    logging_not_lazy: true
    exceptions_raising_non_exception: true
    exceptions_notimplemented_raised: true
    exceptions_broad_except: true
    exceptions_bare_except: true
    basic_exec_used: true
    variables_redefined_outer_name: true
    variables_redefine_in_handler: true
    variables_used_before_assignment: true
    variables_undefined_loop_variable: true
    variables_undefined_all_variable: true
    variables_unbalanced_tuple_unpacking: true
    variables_no_name_in_module: true
    variables_global_variable_undefined: true
    typecheck_unexpected_keyword_arg: true
    typecheck_too_many_function_args: true
    typecheck_not_callable: true
    typecheck_no_value_for_parameter: true
    typecheck_no_member: true
    typecheck_duplicate_keyword_arg: true
    typecheck_assignment_from_no_return: true
    string_too_many_format_args: true
    string_constant_anomalous_unicode_escape_in_string: true
    open_mode_bad_open_mode: true
    logging_too_many_args: true
    imports_import_self: true
    exceptions_raising_bad_type: true
    exceptions_catching_non_exception: true
    classes_non_parent_init_called: true
    classes_non_iterator_returned: true
    classes_bad_context_manager: true
    classes_access_member_before_definition: true
    basic_return_in_init: true
    basic_not_in_loop: true
    basic_function_redefined: true
    basic_bad_reversed_sequence: true
    basic_abstract_class_instantiated: true
    string_constant_anomalous_backslash_in_string: true
    newstyle_bad_super_call: true
    imports_cyclic_import: true
    classes_super_init_not_called: true
    classes_method_hidden: true
    classes_arguments_differ: true
    basic_useless_else_on_loop: true
    basic_expression_not_assigned: true
  javascript:
    code_rating: true
    # duplicate_code: true
    unsafe_undefined: true
    var_sometimes_initialized: true
    var_never_initialized: true
    valid_typeof: false
    use_isnan: true
    unsafe_mutable_variable_usage: true
    nsp_vulnerabilities: false
    no_with: true
    no_void: true
    no_use_before_define: true
    no_unused_vars: false
    no_unused_function: false
    no_param_assign: true
    no_implicit_undefined_return: true
    no_alert: true
    eqeqeq: true
    no_var: false
    no_loop_var_assign: true
    no_else_return: true
    check_for_loops_test: false
    check_loop_no_body: false
    check_switch_ambiguous_test: true
    check_switch_default_only: false
    check_switch_default_not_last: true
    check_switch_no_default: false
    'check_switch_no_uncommented_fallthrough"': false
    'check_switch_unintended label': false
    check_too_many_arguments: true
    check_undeclared_vars: true
    check_try_statement: true
    check_unnecessary_continue: false
    check_unnecessary_return: false
    check_unused_member_calls: false
    check_unused_object_creation: false
    check_unused_parameters: false
    consistent_return: true
    curly: true
    guard_for_in: true
    jsdoc_no_duplicate_params: false
    jsdoc_non_existent_params: true
    new_cap: true
    no_alias_builtins: false
    no_array_constructor: true
    no_bitwise: false
    no_dupe_keys: true
    no_delete_var: true
    no_debugger: false
    no_constant_condition: true
    no_console: false
    no_comma_dangle: false
    no_caller: true
    no_invalid_regexp: true
    no_inner_declarations: true
    no_implied_eval: true
    no_func_assign: true
    no_extra_bind: false
    no_extend_native: true
    no_ex_assign: true
    no_eval: true
    no_empty_label: false
    no_empty_class: false
    no_empty: true
    no_label_var: true
    no_native_reassign: true
    no_negated_in_lhs: false
    no_new_func: true
    no_new_require: false
    no_new_wrappers: false
    no_path_concat: true
    no_process_exit: true
    no_redeclare: true
    no_redeclared_const: false
    no_return_assign: true
    no_sequences: true
    no_shadow_builtins: false
    no_sparse_arrays: false
    no_undef: true
    no_undef_init: true
    no_unreachable: false
    no_unused_assignment: false
    no_unused_const: false
    no_unused_expressions: false
tools:
  pylint:
    python_version: '3'
    # config_file: .pylintrc
filter:
  excluded_paths:
    - '*/vendor/*'
